/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ZyncPair = t.iface([], {
  "source": "string",
  "destination": "string",
});

export const ZyncProjectConfig = t.iface([], {
  "name": "string",
  "baseDestinationPath": "string",
  "paths": t.array("ZyncPair"),
});

export const ZyncConfig = t.iface([], {
  "projects": t.array("ZyncProjectConfig"),
  "baseSourcePath": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  ZyncPair,
  ZyncProjectConfig,
  ZyncConfig,
};
export default exportedTypeSuite;
